### ISSUE TITLE
Стабілізація Live

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#77]
500 помилка, підняв через
```
rhc ssh live
cd app-root/repo/
node start
```
## Можливі причини: 
* помилки при роботі з БД, бо змінилася її структура.
* інша проблема з БД — наприклад, не змогла обробити запит.

## Треба:
- [x] Розібратись, чи досить цих кроків.
- [x] Перевірити логи: `rhc tail live`
- [ ] Зробити автоматичний моніторинг, щоб мейл про падіння приходив якнайшвидше — sentry.io?
- [ ] Розглянути можливість автоматичного перезапуску
- [ ] Розробити скрипт міграції БД при поновленнях
- [x] Знайти і виправити помилку, яка призводить до падіння. Update: виправлено у #78

**Comment by rostag** [comment]
Перевірив лог, є помилка:

```
==> app-root/logs/nodejs.log <==
find this donation target by target type undefined
events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'targetType' of undefined
    at DBDonation.addDonationToTarget (/var/lib/openshift/57add04f7628e19d630000f8/app-root/runtime/repo/server/mongo/db-donation.js:58:20)
    at /var/lib/openshift/57add04f7628e19d630000f8/app-root/runtime/repo/node_modules/mongoose/lib/model.js:3324:16
    at /var/lib/openshift/57add04f7628e19d630000f8/app-root/runtime/repo/node_modules/mongoose/lib/document.js:1932:15
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
